### ISSUE TITLE
Kargo ücretinin taksitli satışta takside eklenmemesi

### ISSUE THREAD

**Issue by wizz007** [sabitertan/webpos#1]
sabit kargo ya da ağırlığa göre kargo işlemlerinde kargo ücretininde taksitli işlemlerde işlem yansıtılmalı. Kredi kartından çekim yaparken 2 ayrı çekim mi yapıyor. Hem 3x33=99TL hemde 12TL kargo ücreti gibi bunun yerine 3x37=111TL şeklinde olması lazım

**Comment by sabitertan** [comment]
wespos son olarak tüm herşey dahil fiyatı taksit sayısına bölüp o şekilde yolluyor bankaya yani sizin örneğinizde olduğu gibi 3x37=111 olarak, ancak müşteri ürün sayfasındaki tabda gördüğüyle haraket ettiği için bu şekilde bıraktım, belki daha sonra seçimli bir özellik olarak eklenebilir.

**Comment by wizz007** [comment]
yakın zamanda değişiklik yaptınız mı bilmiyorum ama taksit hesaplama kısmında kargo ücreti varsa o ücreti de hesaplatıp toplam fiyata ekleme yaparak düzelttim. Güzel bir modül olmuş ellerinize sağlık.
