### ISSUE TITLE
Notice: Error: Table 'cudi_test.oc_webposbank' doesn't exist

### ISSUE THREAD

**Issue by Arshimet** [sabitertan/webpos#11]
Merhaba. 
ne yaptıoysam olmadı. 
sanki mysql de bu tablo yokmuş gibi davranmakta. bu konuda yardımcı olursanız sevinirim...

**Comment by flightlesstux** [comment]
Merhaba,

Sistemde veritabanı hatası oluşmuş. Aşağıdaki sorguyu mysql veritabanınızda çalıştırabilirsiniz.

```
CREATE TABLE `oc_webposbank` (
`bank_id` int(11) NOT NULL AUTO_INCREMENT,
`name` varchar(64) NOT NULL,
`image` varchar(64) NOT NULL,
`method` varchar(64) NOT NULL,
`model` varchar(64) NOT NULL,
`short` varchar(64) NOT NULL,
`status` tinyint(1) NOT NULL,
PRIMARY KEY (`bank_id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
```

**Comment by muratasan97** [comment]
Kurulumu sorunsuz yaptım izinleri verdim eklenti kur dan web posu aktif etcem ama bu hatayı alıyorum panelde. Veri tabanına girdim baktım orda tabloyu bulamadım ama oluşturmayı da yapamadım. Sorunun bir çözümü varsa detaylı anlatabilirmisiniz. Sitemizde ödeme konusunda sıkıntı var şuanda yardımınızı bekliyorum.

Notice: Error: Table 'u984450955_1.oc_webposbank' doesn't exist
Error No: 1146
SELECT \* FROM oc_webposbank ORDER BY bank_id ASC in /home/u984450955/public_html/system/library/db/mysqli.php on line 40Notice: Trying to get property of non-object in /home/u984450955/public_html/admin/model/extension/webposbuilder.php on line 77Warning: Invalid argument supplied for foreach() in /home/u984450955/public_html/admin/controller/payment/webpos.php on line 143

**Comment by muratasan97** [comment]
Sorunum çözüldü; nasıl olduğunuda söylim wiki deki kurulum rehberindeki gibi adımları izlerseniz düzeliyor. Herkese asıl dikkat etmesi gerektiği adımı söylicem modül sayfasının yenilenmesi çok önemli onu unutursanız izinleri vermeniz işe yaramicaktır.
