### ISSUE TITLE
Notice: Undefined index: total in

### ISSUE THREAD

**Issue by alisanuzundemir** [sabitertan/webpos#13]
Notice: Undefined index: total in /home/aliuzu/freelancedestek.com/catalog/model/total/sub_total.php on line 21

Merhabalar Ödeme sayfasında böyle bir hata ile karşılaşıyorum 5 saattir uğraşıyorum bulamadım nedeni ne olabilir. Lütfen yardım eder misiniz ? 

Tam hata metni aşağıdaki gibidir.

Notice: Undefined index: total in /home/aliuzu/freelancedestek.com/catalog/model/total/sub_total.php on line 21

Notice: Undefined index: total in /home/aliuzu/freelancedestek.com/catalog/model/total/shipping.php on line 24Notice: Undefined index: taxes in /home/aliuzu/freelancedestek.com/catalog/model/total/tax.php on line 4

Warning: Invalid argument supplied for foreach() in /home/aliuzu/freelancedestek.com/catalog/model/total/tax.php on line 4

Notice: Undefined index: total in /home/aliuzu/freelancedestek.com/catalog/model/total/total.php on line 9

**Comment by emehmet** [comment]
örnek $data['total'] diye bir değişken kullanmışsınız. Ama tanımlanmamış. Diğerleri içinde geçerli aynı şey.
