### ISSUE TITLE
Sipariş onayla kısmında hata çıkıyor.

### ISSUE THREAD

**Issue by bilalcancakir** [sabitertan/webpos#17]
Merhaba hocam;

Aşağıdaki hatayı almaktayım çok araştırdım bu modüldeki alınan hataları fakat maalesef bulamadım. webpos.tpl dosyasını bulamadığını söylüyor ama dosyalarım yerli yerinde. Daha önce karşılaşmış olabilir misiniz bu hata ile. Opencart 2.x versiyonunu kullanıyorum. 

Notice: Error: Could not load template /home/natural/public_html/catalog/view/theme/default/template/default/template/payment/webpos.tpl! in /home/natural/public_html/system/storage/modification/system/library/template/basic.php on line 26

**Comment by flightlesstux** [comment]
Merhaba,

2.x versiyonundan tam versiyon sürümünüz nedir acaba?

**Comment by muratasan97** [comment]
2.0.3.1 versiyon  webpos modulunde sipariş ödeme içiçn kart bilgileirni yazıpıyorum tamamla butonu hiç tepki vermiyor bunun sebebi ve çzöümü nasıl olur yardım edermisiniz
