### ISSUE TITLE
Permission hatası

### ISSUE THREAD

**Issue by guncebektas** [sabitertan/webpos#3]
Hocam selamlar, 

Opencart_2.0.3.1 sürümüne eklentiyi kurdum ancak banka ekleme sayfasında şöyle bir hata alıyorum.

You do not have permission to access this page, please refer to your system administrator.

![issue_webpos](https://cloud.githubusercontent.com/assets/1319474/9294077/b829f3dc-444a-11e5-850d-cd84c2d2c1e3.png)

Controller'daki validateForm'u 

protected function validateForm() {
  return true;
}

şekline getirmeme rağmen bir değişiklik olmadı. Nereyi atlıyorum, teşekkürler.

**Comment by wizz007** [comment]
kullanıcı izinlerini verdiniz mi?

**Comment by guncebektas** [comment]
Teşekkürler, ayrı bir bölüm varmış bunun için şimdi farkettim
