### ISSUE TITLE
checkout sonrası reponse yok

### ISSUE THREAD

**Issue by SabriKorkmaz** [sabitertan/webpos#5]
Selamlar, payment/webpos/send adresine request gidiyor fakat herhangi bir response yok. Sorun neden olabilir ?

**Comment by sabitertan** [comment]
Kurulumda neler yaptınız? Opencart sürüm numaranız nedir? Hangi banka hangi yöntemde bu sorunla karşılaştınız? Test mi Gerçek Ödeme mi?

**Comment by ghost** [comment]
Merhaba, Son adımda ödeme işlemi yapılamıyor. Sorunun bir çözümü var mıdır?
Opencart Sürüm 2.0.3.1
Akbank , nestpay , 3d_model , 1
index.php?route=payment/webpos/send işleminden dönüş alınamamaktadır.
Ne gibi değişiklik yapmak gerekiyor?

**Comment by sabitertan** [comment]
Wikideki kurulum adımlarını takip ederek tekrar kurunuz sorun devam ederse paylaşınız.

**Comment by ozerkurnaz** [comment]
Merhaba hocam sürüm 2.0.3.1
işbankası nestpay classic 1 
karttan çekim yapıyor ancak herhangi bir uyarı vermiyor çekim yapıldığına dair .
kurulum adımlarınızı tam olarak yaptım hiç bir sorun gözükmüyor bu konuda yardımcı olabilirmisiniz.

**Comment by ozerkurnaz** [comment]
Hata kayıtlarında bu hatayı veriyor:
2015-12-05 1:25:02 - PHP Notice:  Undefined index: taksit in /home/kirmizibeyazkitap.com/httpdocs/opencartdeneme/system/helper/webpos/adapter/nestpay/nestpayclassic.php on line 24
2015-12-05 1:25:02 - PHP Notice:  Undefined index: message in /home/kirmizibeyazkitap.com/httpdocs/opencartdeneme/system/helper/webpos/adapter/nestpay/nestpayclassic.php on line 52

**Comment by sabitertan** [comment]
@ozerkurnaz Geri bildiriminiz için teşekkürler. Hata giderildi.

masterdan webpos/upload/system/helper/webpos/adapter/nestpay/nestpayclassic.php 

dosyasını indirip kullanabilirsiniz.

**Comment by muhammetali** [comment]
@ozerkurnaz Geri bildiriminiz için teşekkürler. Hata giderildi.

masterdan webpos/upload/system/helper/webpos/adapter/nestpay/nestpayclassic.php

dosyasını indirip kullanabilirsiniz.

Hocam benim sitede aynı hatayı veriyordu dediğiniz düzeltmeyi yaptıktan sonra 
bu hatayı "error" alıyorum. hata günlüğünede bir şey yazmıyor.

**Comment by dnzgnr** [comment]
Merhaba gerçek ortam kullanıyoruz garanti bankası ödeme alınıyor fakat payment/webpos/send adresine request ediyor ödeme tamamlandı sayfasına bir türlü geçmiyor, aynı ekranda kalıyor sepettede ürünler duruyor.
