### ISSUE TITLE
BIN Kodu ile ilgili Response

### ISSUE THREAD

**Issue by caglarergul** [sabitertan/webpos#6]
Merhaba Sabit bey, Opencart 2.0.3.1'e webpos kurdum.
Aşağıdaki sorunu çözemedim, BIN ile ilgili bir bilgi bulunmuyor config'de.

İlginiz için teşekkürler.

Notice: Undefined index: cc_number in /alfa/system/helper/webpos/adapter/gvp/gvpclassic.php on line 28

Notice: Undefined index: cc_expire_date_month in /alfa/system/helper/webpos/adapter/gvp/gvpclassic.php on line 29

Notice: Undefined index: cc_expire_date_year in /alfa/system/helper/webpos/adapter/gvp/gvpclassic.php on line 29

Notice: Undefined index: cc_number in /alfa/system/helper/webpos/adapter/gvp/gvpclassic.php on line 39

Notice: Undefined index: cc_cvv2 in /alfa/system/helper/webpos/adapter/gvp/gvpclassic.php on line 41

{"error":"BIN tanimi bulunamadi."}

**Comment by sabitertan** [comment]
Öncelikle kullandığınız sistemin GVP klasik olduğunu bankadan doğrulayın ve ardından bankanın verdiği bilgileri doğru olarak yönetim panelinden girdiğinizden emin olun. sorun devam ederse buradayız bekleriz :)

**Comment by caglarergul** [comment]
Teşekkürler. Banka destekliyormuş, ama aynı hatayı almaya devam ettim. Ardından gvphosting modelini denedim. sonuç aşağıdaki hata kodu

<GVPSResponse>
<Transaction>
<Response><ErrorCode>0001</ErrorCode>
<ErrorMessage>Giriş yaptığınız değerleri kontrol ediniz</ErrorMessage>
<Source>GVPS</Source>
<Code>92</Code>
<ReasonCode>0001</ReasonCode>
<Message>Declined</Message>
<ErrorMsg>Giriş yaptığınız değerleri kontrol ediniz</ErrorMsg>
<SysErrMsg>Giriş yaptığınız değerleri kontrol ediniz</SysErrMsg>
</Response>
</Transaction>
</GVPSResponse>

**Comment by caglarergul** [comment]
Tamam sorun çözüldü, teşekkürler ilgin için :)
