### ISSUE TITLE
payment sonrası confirm

### ISSUE THREAD

**Issue by guncebektas** [sabitertan/webpos#7]
hocam selamlar, banka kurulumu vs tamam ancak en son işlemde son tuşa tıkladığımda payment/send ajax işlemi çalışmıyor hiçbir şekilde uyarıda vermiyor. bunun sebebi ne olabilir. sitemiz teknofix.com.tr/demo adresinde oc2, ücretli yardım edebilirseniz bu akşam görüşmek isterim

**Comment by sabitertan** [comment]
Son ekranda webpos/send işlemini çalıştıran ajax kodunda değişiklik yapmışsınız ve 'data' değişkenini post etmemişsiniz, data değişkenini json olarak post etmeniz lazım.

**Comment by guncebektas** [comment]
aslında o şekildeydi ama ben deneme amaçlı olarak o şekle getirdim

**Comment by guncebektas** [comment]
console a log düşmüyormuş ama networkte 
<b>Warning</b>: simplexml_load_string(): Entity: line 1: parser error : Opening and ending tag mismatch: url line 1 and SysErrMsg in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>48</b><b>Warning</b>: simplexml_load_string(): sponse><Transaction><Response><SysErrMsg>cUrl Error: <url> malformed</SysErrMsg> in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>48</b><b>Warning</b>: simplexml_load_string():                                                                                ^ in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>48</b><b>Warning</b>: simplexml_load_string(): Entity: line 1: parser error : Opening and ending tag mismatch: SysErrMsg line 1 and Response in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>48</b><b>Warning</b>: simplexml_load_string(): nsaction><Response><SysErrMsg>cUrl Error: <url> malformed</SysErrMsg></Response> in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>48</b><b>Warning</b>: simplexml_load_string():                                                                                ^ in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>48</b><b>Warning</b>: simplexml_load_string(): Entity: line 1: parser error : Opening and ending tag mismatch: Response line 1 and Transaction in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>48</b><b>Warning</b>: simplexml_load_string(): onse><SysErrMsg>cUrl Error: <url> malformed</SysErrMsg></Response></Transaction> in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>48</b><b>Warning</b>: simplexml_load_string():                                                                                ^ in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>48</b><b>Warning</b>: simplexml_load_string(): Entity: line 1: parser error : Opening and ending tag mismatch: Transaction line 1 and GVPSResponse in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>48</b><b>Warning</b>: simplexml_load_string(): >cUrl Error: <url> malformed</SysErrMsg></Response></Transaction></GVPSResponse> in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>48</b><b>Warning</b>: simplexml_load_string():                                                                                ^ in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>48</b><b>Warning</b>: simplexml_load_string(): Entity: line 1: parser error : Premature end of data in tag GVPSResponse line 1 in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>48</b><b>Warning</b>: simplexml_load_string(): >cUrl Error: <url> malformed</SysErrMsg></Response></Transaction></GVPSResponse> in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>48</b><b>Warning</b>: simplexml_load_string():                                                                                ^ in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>48</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>49</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>49</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>49</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>50</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>50</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>50</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>62</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>62</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>62</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>63</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>63</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>63</b>{"error":""}

hatası aldım, kontrol ediyorum

**Comment by guncebektas** [comment]
son durum
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body>
<P>Donus icin isyeri URL bulunamiyor, Karti basan banka sisteminden gelen hatali PARes mesaji veya sistem hatasi
</body>
</html>
<b>Notice</b>: Undefined index: REASONCODE in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>150</b><b>Notice</b>: Undefined index:  in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>150</b><br />İşlem Başarısız<b>Warning</b>: simplexml_load_string(): Entity: line 4: parser error : Opening and ending tag mismatch: meta line 3 and head in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>52</b><b>Warning</b>: simplexml_load_string(): </head> in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>52</b><b>Warning</b>: simplexml_load_string():        ^ in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>52</b><b>Warning</b>: simplexml_load_string(): Entity: line 7: parser error : Opening and ending tag mismatch: P line 6 and body in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>52</b><b>Warning</b>: simplexml_load_string(): </body> in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>52</b><b>Warning</b>: simplexml_load_string():        ^ in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>52</b><b>Warning</b>: simplexml_load_string(): Entity: line 8: parser error : Opening and ending tag mismatch: body line 5 and html in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>52</b><b>Warning</b>: simplexml_load_string(): </html> in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>52</b><b>Warning</b>: simplexml_load_string():        ^ in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>52</b><b>Warning</b>: simplexml_load_string(): Entity: line 9: parser error : Premature end of data in tag head line 2 in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>52</b><b>Warning</b>: simplexml_load_string():  in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>52</b><b>Warning</b>: simplexml_load_string(): ^ in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>52</b><b>Warning</b>: simplexml_load_string(): Entity: line 9: parser error : Premature end of data in tag html line 1 in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>52</b><b>Warning</b>: simplexml_load_string():  in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>52</b><b>Warning</b>: simplexml_load_string(): ^ in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>52</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>54</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>54</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>54</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>55</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>55</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>55</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>67</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>67</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>67</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>68</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>68</b><b>Notice</b>: Trying to get property of non-object in <b>/vhosts/teknofix.com.tr/http/demo/system/helper/webpos/adapter/gvp/gvpclassic.php</b> on line <b>68</b>{"error":""}

**Comment by guncebektas** [comment]
en son buraya kadar geldim {"error":"ErrorId: 0752"} tanımı Terminal kaydı yok. ErrorId: 0752 şeklindeymiş.

**Comment by sabitertan** [comment]
Benzer sorunlar yaşayan arkadaşlar webpos.ocmod.xml dosyasını masterdan indirip kurulması gerekmektedir. Lütfen wiki sayfasında Kurulum adımlarını dikkatlice takip ediniz.
