### ISSUE TITLE
Opencart 2.1 mysql hatası

### ISSUE THREAD

**Issue by gurkankara** [sabitertan/webpos#8]
Kurulum sonrasında mysql table oluşturamıyor sanırım. Aşağıdaki hatayı alıyorum. 

Notice: Error: Table 'op_db.oc_webposbank' doesn't exist

Ayrıca ocmod ile yükleyince yetki hatası veriyor ve eklenti ayarlarına giremiyorum. Kullanıcı grup ayarlarında da yetkilendirme kısmında çıkmıyor modül. Dosyaları ftp üzerinden upload edip, XML'i de eklenti yükle kısmından tek olarak atınca ancak bu sorun çözülüyor.

**Comment by sabitertan** [comment]
Kurulum adımları wikiye eklendi. install.xml yi iptal ettim çünkü FTP ayarlarında sorun olan çok kullanıcı var. Kurulum adımları dikkatlice takip edilirse sorun olmayacaktır.
